In [1]:
# =========================================
# STEP 1: Install & Import Libraries
# =========================================
!pip install gymnasium numpy

import numpy as np
import gymnasium as gym
import random

# =========================================
# STEP 2: Create Environment
# =========================================
env = gym.make("FrozenLake-v1", is_slippery=False)  # deterministic for learning

# Number of states and actions
state_size = env.observation_space.n
action_size = env.action_space.n

print("States:", state_size)
print("Actions:", action_size)

# =========================================
# STEP 3: Initialize Q-Table
# =========================================
q_table = np.zeros((state_size, action_size))

# =========================================
# STEP 4: Hyperparameters
# =========================================
learning_rate = 0.8
discount_rate = 0.95

epsilon = 1.0        # exploration rate
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

episodes = 1000
max_steps = 100

# =========================================
# STEP 5: Training (Q-Learning)
# =========================================
for episode in range(episodes):
    state, _ = env.reset()
    done = False

    for step in range(max_steps):
        # Exploration vs Exploitation
        if random.uniform(0,1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state,:])

        # Take action
        new_state, reward, done, truncated, _ = env.step(action)

        # Q-Learning Formula
        q_table[state, action] = q_table[state, action] + learning_rate * (
            reward + discount_rate * np.max(q_table[new_state,:]) - q_table[state, action]
        )

        state = new_state

        if done or truncated:
            break

    # Decay epsilon
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)

# =========================================
# STEP 6: Show Learned Q-Table
# =========================================
print("\nQ-Table:")
print(q_table)

# =========================================
# STEP 7: Test the Agent
# =========================================
print("\nTesting trained agent:\n")

for episode in range(5):
    state, _ = env.reset()
    done = False
    print(f"Episode {episode+1}")

    for step in range(max_steps):
        action = np.argmax(q_table[state,:])
        new_state, reward, done, truncated, _ = env.step(action)

        print(f"Step {step}: State {state} → Action {action}")

        state = new_state

        if done or truncated:
            if reward == 1:
                print("✅ Reached Goal!")
            else:
                print("❌ Fell into hole")
            print()
            break

env.close()

States: 16
Actions: 4

Q-Table:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Testing trained agent:

Episode 1
Step 0: State 0 → Action 0
Step 1: State 0 → Action 0
Step 2: State 0 → Action 0
Step 3: State 0 → Action 0
Step 4: State 0 → Action 0
Step 5: State 0 → Action 0
Step 6: State 0 → Action 0
Step 7: State 0 → Action 0
Step 8: State 0 → Action 0
Step 9: State 0 → Action 0
Step 10: State 0 → Action 0
Step 11: State 0 → Action 0
Step 12: State 0 → Action 0
Step 13: State 0 → Action 0
Step 14: State 0 → Action 0
Step 15: State 0 → Action 0
Step 16: State 0 → Action 0
Step 17: State 0 → Action 0
Step 18: State 0 → Action 0
Step 19: State 0 → Action 0
Step 20: State 0 → Action 0
Step 21: State 0 → Action 0
Step 22: State 0 → Action 0
Step 23: State 0 → Action 0
Step 24: State 0 → Action 0
St